export const FETCH_COURSES_REQUEST = "FETCH_COURSES_REQUEST"; 
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS"; 
export const FETCH_COURSES_FAILURE = "FETCH_COURSES_FAILURE"; 

export const FETCH_ONE_COURSE_REQUEST = "FETCH_ONE_COURSE_REQUEST"; 
export const FETCH_ONE_COURSE_SUCCESS = "FETCH_ONE_COURSE_SUCCESS"; 
export const FETCH_ONE_COURSE_FAILURE = "FETCH_ONE_COURSE_FAILURE"; 